name: Sync cloudformation script to S3
on: 
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@master
     - uses: tpaschalis/s3-sync-action@master
       with:
         args: --acl public-read
       env:
         FILE: ./yugabyte_cloudformation.yaml
         AWS_REGION: 'us-west-2'
         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     
